export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const PURSHASE_BURGER_SUCCESS = 'PURSHASE_BURGER_SUCCESS';
export const PURSHASE_BURGER_FAIL = 'PURSHASE_BURGER_FAIL';
export const PURSHASE_BURGER_START = 'PURSHASE_BURGER_START';